### ISSUE TITLE
Numpy is green, while no Windows wheels are available at PyPi!

### ISSUE THREAD

**Issue by fladd** [meshy/pythonwheels#56] opened 2015-05-11 10:23 UTC
It seems a bit odd to me that a package is marked green as soon as wheels for a single platform are available on PyPi. It gives the impression that it is a good idea to rely on PIP and PyPi to take care of dependencies when this is clearly not the case.

**Comment by meshy** [comment] 2015-05-11 10:31
Hi there, thanks for the report. This is a duplicate of https://github.com/meshy/pythonwheels/issues/48, and the inverse of #2. I hope you don't mind me closing this issue so that discussion can continue in the other threads.

**Closed by meshy** 2015-05-11 10:31 UTC
